# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

remote:
  ssh: ''
  path: ''

# Note that a local gurobi.lic file takes precedence over this setting
solving:
  solver_options:
    gurobi-default:
      env:
        WLSACCESSID: ''
        WLSSECRET: ''
        LICENSEID:
